"""empty message

Revision ID: 05820900b098
Revises: 83c69e0d88dc
Create Date: 2017-06-26 09:01:45.740009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05820900b098'
down_revision = '83c69e0d88dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postVersions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('version_intro', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postVersions_timestamp'), 'postVersions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_postVersions_version'), 'postVersions', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postVersions_version'), table_name='postVersions')
    op.drop_index(op.f('ix_postVersions_timestamp'), table_name='postVersions')
    op.drop_table('postVersions')
    op.drop_table('posts')
    # ### end Alembic commands ###
