"""empty message

Revision ID: 73eed53baf49
Revises: 7b43b96d52b8
Create Date: 2017-06-26 10:34:56.395457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73eed53baf49'
down_revision = '7b43b96d52b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postContents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('version_intro', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postContents_timestamp'), 'postContents', ['timestamp'], unique=False)
    op.create_index(op.f('ix_postContents_version'), 'postContents', ['version'], unique=False)
    op.drop_table('postcontents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postcontents',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('version_intro', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='postcontents_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='gbk',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_postContents_version'), table_name='postContents')
    op.drop_index(op.f('ix_postContents_timestamp'), table_name='postContents')
    op.drop_table('postContents')
    # ### end Alembic commands ###
