"""empty message

Revision ID: 7c25edfd74f4
Revises: 3d999977e58b
Create Date: 2017-07-05 17:54:26.365961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c25edfd74f4'
down_revision = '3d999977e58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('messages', sa.Column('readed', sa.BOOLEAN(), nullable=True))
    op.add_column('messages', sa.Column('switch', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'switch')
    op.drop_column('messages', 'readed')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ibfk_4', 'comments', 'postcontents', ['postContent_id'], ['id'])
    op.create_table('postcontents',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('version_intro', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='postcontents_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_postContents_version'), table_name='postContents')
    op.drop_index(op.f('ix_postContents_timestamp'), table_name='postContents')
    op.drop_table('postContents')
    # ### end Alembic commands ###
