"""empty message

Revision ID: a3ca19b32519
Revises: 71470c773add
Create Date: 2017-07-07 15:28:17.217910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3ca19b32519'
down_revision = '71470c773add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('postContents',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('version', sa.Integer(), nullable=True),
    # sa.Column('version_intro', sa.Text(), nullable=True),
    # sa.Column('timestamp', sa.DateTime(), nullable=True),
    # sa.Column('body', sa.Text(), nullable=True),
    # sa.Column('post_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # # )
    # op.create_index(op.f('ix_postContents_timestamp'), 'postContents', ['timestamp'], unique=False)
    # op.create_index(op.f('ix_postContents_version'), 'postContents', ['version'], unique=True)
    # op.create_table('postContentLikes',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('postContent_id', sa.Integer(), nullable=True),
    # sa.Column('author_id', sa.Integer(), nullable=True),
    # sa.Column('like', sa.BOOLEAN(), nullable=True),
    # sa.Column('dislike', sa.BOOLEAN(), nullable=True),
    # sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    # sa.ForeignKeyConstraint(['postContent_id'], ['postContents.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.create_table('commentLikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('commentlikes')
    # op.drop_table('postcontents')
    # op.drop_table('postcontentlikes')
    # op.drop_constraint('comments_ibfk_2', 'comments', type_='foreignkey')
    # op.create_foreign_key(None, 'comments', 'postContents', ['postContent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ibfk_2', 'comments', 'postcontents', ['postContent_id'], ['id'])
    op.create_table('postcontentlikes',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('postContent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('like', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('dislike', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='postcontentlikes_ibfk_1'),
    sa.ForeignKeyConstraint(['postContent_id'], ['postcontents.id'], name='postcontentlikes_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('postcontents',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('version_intro', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='postcontents_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('commentlikes',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='commentlikes_ibfk_1'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='commentlikes_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('commentLikes')
    op.drop_table('postContentLikes')
    op.drop_index(op.f('ix_postContents_version'), table_name='postContents')
    op.drop_index(op.f('ix_postContents_timestamp'), table_name='postContents')
    op.drop_table('postContents')
    # ### end Alembic commands ###
